# 注意：v2.6.1 需完全删除 version 字段，否则会报版本不支持错误
version: "2"
# 运行配置（v2.x 字段名调整）
run:
  timeout: 5m                # 5分钟超时（替代原 deadline）
  tests: true                # 检查测试文件
  go: "1.25"                 # 适配你的 Go 1.25.3 版本
  severity: warning          # 仅显示警告及以上级别问题

# Linter 个性化配置（v2.x 字段名改为单数 linter-settings）
linter-settings:
  govet:
    enable-all: true
    disable: []
  gocyclo:
    min-complexity: 10
  misspell:
    locale: US
  funlen:
    lines: 50
    statements: 25
  revive:
    severity: warning
    confidence: 0.8
    rules:
      - name: var-naming
      - name: package-comments
      - name: line-length-limit
        arguments: [120]
      - name: unused-parameter
  lll:
    line-length: 120
    tab-width: 4

# 启用/禁用的 Linter（移除 gofumpt）
linters:
  enable:
    - revive
    - govet
    - staticcheck
    - gosec
    - gocyclo
    - misspell
    - ineffassign
    - unused
    - errcheck
    - gochecknoinits
    - goconst
    - funlen
    - lll
    - prealloc
    - errorlint          # 检查Go 1.13+错误包装规范（和你问的defer err check强相关）
    - nilerr             # 检测"判断err≠nil但返回nil"的逻辑bug
    - wrapcheck          # 检查外部包错误是否包装（错误处理最佳实践）
    - bodyclose          # 检查HTTP响应体是否关闭（避免资源泄漏）
    - nolintlint         # 检查nolint注释是否规范（避免无效nolint）
    - nakedret           # 检查过长的裸返回函数（提升可读性）
    - nestif             # 检查深层嵌套if（降低代码复杂度）
    - unconvert          # 移除不必要的类型转换（优化代码）
    - whitespace         # 检查不必要的空白符（auto-fix，规范格式）
    - gocognit           # 检查认知复杂度（补充gocyclo的复杂度检查）
    - godot              # 检查注释是否以句点结尾（规范注释，auto-fix）
    - makezero           # 检查切片非零初始长度（补充prealloc的内存优化）
    - copyloopvar        # 检查循环变量拷贝问题（Go常见坑，auto-fix）
  disable: []  # 空数组，避免 null 报错

# 输出配置（v2.x 仅保留 formatter）
output:
  formatter: colored-line-number  # 带颜色的行号输出格式

# 问题排除规则（v2.x 中 exclude-rules 改名为 exclude）
issues:
  exclude:
    - path: _test\.go
      linters:
        - funlen
        - gocyclo
        - lll
        - nakedret       # 测试函数允许裸返回
        - nestif         # 测试函数允许深层嵌套if
        - gocognit       # 测试函数允许高认知复杂度
  # 最多显示问题数限制
  max-issues-per-linter: 100
  max-same-issues: 50